<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Vuleticd
 * @package     Vuleticd_Assist
 * @copyright   Copyright (c) 2015 Vuletic Dragan (http://www.vuleticd.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Vuleticd\Assist\Block\Redirect
 */
?>
<html>
<head>
</head>
<body>
<b><?php echo __('You will be redirected to ASSIST in a few seconds.'); ?></b>
<form id="assist_form" method="POST" action="<?php /* @escapeNotVerified */ echo $block->getFormAction()?>">
	<?php if (is_array($block->getFormData())): ?>
        <?php foreach ($block->getFormData() as $name => $value): ?>
            <input type="hidden" name="<?php echo $name; ?>" <?php if (!is_null($value)) { echo 'value="'. $value . '"'; } ?> />
        <?php endforeach; ?>
    <?php endif; ?>
</form>
<script>
    document.getElementById('assist_form').submit();
</script>
</body>
</html>